Add system property to ignore invokedynamic types
FabricMC/tiny-remapper pull request #106
Opened 2023-03-19 20:12 UTC by lukebemish

I've recently ran up against #26 in a project of mine - I get so much log spam due to tiny-remapper finding groovy indy instructions that it cannot remap that it is impossible to see any actual issues in the logs. I would like some way of turning off that warning for specific indy instructions, similar to what is already done for string concatenation. This PR adds a system property, `net.fabricmc.tinyremapper.knownindybsm` (this could definitely change, I'm by no means sold on it) for providing a list of instructions that tiny-remapper can safely assume do not need to be remapped.

If you think there may be a better approach to this than a system property, please let me know, and I can see about implementing that.

2023-06-13 10:02 UTC, modmuss50 requested changes

2023-06-13 10:02 UTC, modmuss50 commented on src/main/java/net/fabricmc/tinyremapper/AsmClassRemapper.java
> +		private static final Set<String> ALLOWED_INDY_BSM = Stream.of(System.getProperty("net.fabricmc.tinyremapper.knownindybsm", "").split(",")).collect(Collectors.toSet());
This should be set via the CLI and via the TinyRemapper.Builder. See how `forcePropagation` is set.

2023-06-13 10:02 UTC, modmuss50 commented on src/main/java/net/fabricmc/tinyremapper/AsmClassRemapper.java
> -					|| bsm.getOwner().equals("java/lang/runtime/ObjectMethods")) {
I think it would also be best to move these into the set.

2023-06-13 11:19 UTC, modmuss50 commented
Another option with this is to just not log issues at all, or maybe log it once (when a flag is set?)

2023-07-15 03:39 UTC, lukebemish commented
Alright, I *think* I hooked that up to the CLI system in a way that makes sense; let me know if not. I'm not quite sure enough about how TR works to try poking at adding the "warn only once" system, but that could always be added later as well.

2023-08-14 08:53 UTC, modmuss50 approved these changes

2023-08-14 08:54 UTC, modmuss50 commented on src/main/java/net/fabricmc/tinyremapper/Main.java
>  import java.io.FileReader;
```suggestion
```
Removing this unused import.

2023-08-14 08:56 UTC, merged